### PR TITLE
Refactoring: Tag & BaseValue removed

### PR DESCRIPTION
**Pull request by hendrikebbers**
- Removed unneeded functionality

### CODE REVIEW

**Comment by Dierk** [comment]
You are removing dirty handling and tags?

Dierk

sent from:mobile

**Comment by hendrikebbers** [comment]
Yes, for DP Beans / Properties only the "VALUE" tag is used. In addition we do not need a baseValue. By removing them we do not need to refactor unused code and the commands (in JSON) are smaller since the tag & base value attributes are not send.

**Comment by Dierk** [comment]
How much bandwidth is saved? Did you measure?

**Comment by hendrikebbers** [comment]
Nope, but the saved bandwidth is just a side effect (no baseValue / tag attribute in AttributeCreationCommand). This was done since the code is only used by unit test and by no framework calls. Based on this it will make the code easier.

**Comment by kunsingh** [comment]
Why we did this? Now there will not be any dirty listener on PM.

Please remove tag from all the constructor call - ClientAttributeTests.ts

**Comment by hendrikebbers** [comment]
@kunsingh We do not use BaseValue or Tag in DolphinPlatform. The Java code don't even contain this values anymore. Since we do not use BaseValue we do not need any dirty listener.

About Tag: I thought that I removed it everywhere. I will have a look and remove the missed calls.

**Comment by kunsingh** [comment]
looks good to me. Please remove tag related code from 'ClientAttributeTests.ts' and then merge to master.

**Pull request merged**
